model_options:
  test_size: 0.2
  random_state: 3
  features:
    - engines
    - passenger_capacity
    - crew
    - d_check_complete
    - moon_clearance_complete
    - iata_approved
    - company_rating
    - review_scores_rating

# Hyperparameters for the model
model_params:
  input_size: 1
  n_kernels: 6
  output_size: 10
  epochs: 10
  learning_rate: 0.001